// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://myanoclddbveoshgfjgd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im15YW5vY2xkZGJ2ZW9zaGdmamdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxNjEzMDYsImV4cCI6MjA2MDczNzMwNn0.reABGCw3FgK1FJCqrPRH6Idd8-AFeQ_njq_ODi-Q-N4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);